### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by pallavagarwal07** [srijanshetty/snips#2]
OS: Arch Linux
Using: npm 2.11.3

Error details:

```
$ npm install snips-cli
/
> execSync@1.0.2 install /home/pallav/node_modules/snips-cli/node_modules/copy-paste/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!
snips-cli@1.1.0 ../node_modules/snips-cli
├── shelljs@0.5.1
├── lodash@3.9.3
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── front-matter@1.0.0 (yaml-js@0.1.1)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
└── copy-paste@1.1.2 (iconv-lite@0.4.10, execSync@1.0.2)
```

I don't know node well enough to know whether `node app.js` is supposed to work, but just in case it is, I'm getting the following error:

```
$ node app.js new test
child_process.js:1136
  var err = this._handle.spawn(options);
                         ^
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (child_process.js:1136:26)
    at Object.exports.spawn (child_process.js:995:9)
    at Command.module.exports.createSnippet (/home/pallav/projects/snips/lib/functions.js:59:43)
    at Command.listener (/home/pallav/projects/snips/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/home/pallav/projects/snips/node_modules/commander/index.js:610:12)
    at Command.parse (/home/pallav/projects/snips/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/home/pallav/projects/snips/app.js:38:9)
    at Module._compile (module.js:460:26)
```

**Comment by srijanshetty** [comment]
@pallavagarwal07 : `snips` should work despite the error.

**Comment by srijanshetty** [comment]
@pallavagarwal07 : There seems to be some error with the _copy-paste_ module, I'll have to check with the module author.

**Comment by pallavagarwal07** [comment]
What do you mean, it should work? It exits with that error

**Comment by sakshamsharma** [comment]
Well I had to create the .snips folder manually to atleast be able to edit the template file, and then on saving, I noticed that the content being added to .snipsIndex is giving trouble (unexpected end of input, error at 50:34 in functions.js).

**Comment by sakshamsharma** [comment]
It works fine on my Arch, post the commit I have sent as a pull request. The snips aren't getting indexed though, perhaps I'm using a wrong format to type the tags.
